version: '3'
services:
  server:
    container_name: server
    build: ./
    working_dir: /app
    links:
      - mongodb
    environment:
      MONGODB_URI: mongodb://mongodatabase/mydb
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    command: npm start
  mongodb:
    container_name: mongodatabase
    image: mongo
    ports:
      - "27017:27017"